# Generated by Django 3.1.4 on 2020-12-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_stock_trader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
