# Generated by Django 3.1.4 on 2020-12-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_stock_trader', '0006_auto_20201231_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='share',
            new_name='shares',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='share',
            new_name='shares',
        ),
    ]
